### ISSUE TITLE
Exynos porting instructions missing

### ISSUE THREAD

**Issue by ASDownloadingAccount** [Robotix22/MU-Qcom-Guides#18]
When will it be possible to port to Samsung Exynos again?

**Comment by Robotix22** [comment]
I will hopefully Write an Guide for Tegra and Exynos Soon
So please wait, Until they are Aviable

**Comment by ASDownloadingAccount** [comment]
So it's **only Qualcomm** for now?

**Comment by Robotix22** [comment]
Yes, I already rewrote some Guides, But there is still much to go

**Comment by yusufyorunc** [comment]
'Then extract the .7z Files and push the content with adb push into the workspace folder' I never downloaded a file with .7z extension what are you talking about

**Comment by index986** [comment]
> 'Then extract the .7z Files and push the content with adb push into the workspace folder' I never downloaded a file with .7z extension what are you talking about

wut

**Comment by ASDownloadingAccount** [comment]
> 'Then extract the .7z Files and push the content with adb push into the workspace folder' I never downloaded a file with .7z extension what are you talking about

That doesn't even make any sense at all.
Were you supposed to copy or move the content?

**Comment by Robotix22** [comment]
Please Open a New Issue here, As your Problem isn't Related to this Issue
