### ISSUE TITLE
.

### ISSUE THREAD

**Issue by yusufyorunc** [Robotix22/MU-Qcom-Guides#23]
.

**Comment by Robotix22** [comment]
What Part do you not Understand?

**Comment by yusufyorunc** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/e58a06df-7616-4c44-97e0-6e063f556fad)
Which files are mentioned in the given part

**Comment by Robotix22** [comment]
Right, The Files you need aren't There for some Reason
Here is parted, gdisk isn't needed
[parted.zip](https://github.com/user-attachments/files/16679320/parted.zip)

**Comment by yusufyorunc** [comment]
> Right, The Files you need aren't There for some Reason Here is parted, gdisk isn't needed [parted.zip](https://github.com/user-attachments/files/16679320/parted.zip)

Can you write the steps one by one in order because it doesn't work when I do it and I get confused.

**Comment by Robotix22** [comment]
What do you not understand now?
The Steps should be Clear now

**Comment by yusufyorunc** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/ca0e25e3-e8c9-4c58-b971-b49a5d145528)
![Screenshot_2](https://github.com/user-attachments/assets/7c90c5aa-8d82-4f4c-8a74-e8fcd894d8ef)
Why is this error happening. i have installed all the given

**Comment by Robotix22** [comment]
Remove gdisk, You don't need it, As I said before
