### ISSUE TITLE
Phone doesn't get recognized when doing mass storage under windows

### ISSUE THREAD

**Issue by Ricca665** [Robotix22/MU-Qcom-Guides#25]
This is a weird issue that i have

So basically i decided to follow the official Windows Installation guide to install windows on my Redmi note 11 (spes)

I compiled the UEFI Image to the latest version btw

When i try to do the mass storage thing what happens is basically that under windows it just disconnects and gives nothing

But under linux it recognizes every partition

And this is weird since when i do the command windows decides that the phone is not plugged in anymore

Thanks!

**Comment by Robotix22** [comment]
Which Mass Storage did you use?
The one thats Included in UEFI?

**Comment by Ricca665** [comment]
Nope, the Redmi note 11 GUide (that got linked to the Redmi note 10C one)

**Comment by Robotix22** [comment]
You can try to use the Mass Storage from our UEFI, Hold Volume Down to Enter it
That Requires USB Device Mode tho

**Comment by Ricca665** [comment]
i tried it and it failed

**Comment by Robotix22** [comment]
What did it say?

**Comment by Ricca665** [comment]
Failed to launch Mass Storage Mode!

And then some exception at 0x0000000797A3548

I can't read what exception is because the screen cuts it off, but i think it sais ynchronous

**Comment by Robotix22** [comment]
Would you mind Building Debug?
Then I can tell you whats wrong

**Comment by Ricca665** [comment]
I am sorry for the late reply, i was outside so i couldn't do the thing

Btw here's what it does:

It allocates RAM, loads the drivers and then

Failed to add memory space for 0x600000 0x1D000000! Status = Access Denied
Failed to add memory space for 0x600000 0x60000000! Status = Access Denied
Failed to add memory space for 0x600000 0xE0000000! Status = Access Denied
No RAM Partitions were added, stopping UEFINow.

ASSERT_EFI_ERROR Status = Not Ready

I am really sorry but i can't even take a photo right now because i just have a 2ds as a camera ;-;

**Comment by Robotix22** [comment]
Just Commend that Drtiver then, It will Continue

**Comment by Ricca665** [comment]
what do you mean commend

**Comment by Ricca665** [comment]
and the fact that i am writing this in the first place is because i need windows to apply the .wim file

**Comment by Robotix22** [comment]
Set a `#` before the Include of DynamicRamDxe in APRIORI.inc and DXE.inc
Its Located in `Platform/Xiaomi/spes/Include`

**Comment by Ricca665** [comment]
I have done that and now it works

Now what? i reboot in mass storage mode right?

I am also VERY SORRY for the late reply ;-;

**Comment by Robotix22** [comment]
Yes

**Comment by Ricca665** [comment]
Now other than the expection, it also gives: Data abort: Translation fault, second level

**Comment by Robotix22** [comment]
What do do the Small White Messages at the Side of the Screen say?

**Comment by Ricca665** [comment]
exception at 0x00000007052D820

and then something dxecore.pdb or dxecore.pb (it's too _tiny_)

at the end it says ASSERT ArmCpuDxe DefaultExceptionHandler.c(343); ((BOOLEAN)(0==1))

and the exception found in the release build is still there

**Comment by Robotix22** [comment]
I just Checked if spes has USB Host Mode in UEFI, And it does.
So I give you a New `UsbConfigDxe` which is Device Mode Instead as Mass Storage only works with that.
Just Replace the File in `Binaries/spes/QcomPkg/Drivers/UsbConfigDxe`.
There you go: [UsbConfigDxe-patched.zip](https://github.com/user-attachments/files/16993927/UsbConfigDxe-patched.zip)

**Comment by Ricca665** [comment]
It now DOES boot into mass storage!

I'll let you know if it works or not because linux rn doesn't recognize it

**Comment by Ricca665** [comment]
Now it DOES boot but still windows doesn't recognize it

By unplugging and replugging the usb cable it gives Unknown Port: type 8, and yes i am still in the debug release

**Comment by Robotix22** [comment]
Weird, Did you Try TWRP Mass Storage yet?

**Comment by Ricca665** [comment]
I used orangefox is it ok?

**Comment by Robotix22** [comment]
Yep

**Comment by Ricca665** [comment]
but like with the modified msc.sh from the Redmi Note 10C guide?

That IS the problem, the phone doesn't get recognized under windows, and even tought linux DOES detect it, i need windows tools to finish the installation, that was the reason i made this issue in the first place...

**Comment by Robotix22** [comment]
Redmi 10C is the same SoC, So you don't need to Mod it

**Comment by Ricca665** [comment]
no like the msc.sh script from the guide

**Comment by Robotix22** [comment]
Yeah, You don't need to Mod msc.sh, Or do you mean it dosen't work?

**Comment by Ricca665** [comment]
like the script works in half on my pc

like, as i said, when i run the msc.sh FROM the Redmi note 10C guide, it runs, it unplugs from my pc, and then under linux it detects the partitions. including the windows and esp partitions, but under windows, the pc doesn't recognize the phone, like at all

**Comment by Robotix22** [comment]
Did you try any other USB Ports/USB Cables yet?

**Comment by Ricca665** [comment]
let me try

**Comment by Ricca665** [comment]
btw can i disconnect the cable after i run the script?

**Comment by Robotix22** [comment]
Yes

**Comment by Ricca665** [comment]
I have tried EVERY cable that i had and EVERY port my laptop has and NOTHING

and under linux it detects them, under windows i discovered that it detects it as a MTP device but it doesn't actually mount, and no diskmgmt.msc didn't detect it

I also tried seeing if the partitions were formatted correctly, which they were

my guess is that windows is dumb and it doesn't detect it

**Comment by Ricca665** [comment]
my only options now are either fix the problem on windows or try and find alternatives to dism and bootrec for linux

**Comment by Robotix22** [comment]
I had the Exact Issue but Reversed, Linux just sees a MTP Device, And Windows Sees the Device Correctly
I wasn't able to Fix that, So yeah, You either need to Fix your Windows or Find an Alternative

**Comment by Ricca665** [comment]
It's not even your fault if windows is dumb

**Comment by Ricca665** [comment]
I will try the windows tools alternatives for linux

**Comment by Robotix22** [comment]
Yeah, I hope you Find some, Good Luck on your Way then :D

**Comment by Ricca665** [comment]
Thank you :D

**Comment by Ricca665** [comment]
Now i reopened this issue because i think there is a problem with the EFI ik general

when i do the bcdbolt commands from the guide, they create the efi but it just doesn't boot

my guess is that when running under x86_64 cpu, it creates a x64 UEFI EFI, instead i would need to run windows arm64 to create the proper efi

now i might be dumb but i will let you decide

**Comment by Robotix22** [comment]
I Guess it did Create PC EFI Files, If there is No File named `bootaa64.efi` in `EFI/Boot/` Then Its Broken

**Comment by Ricca665** [comment]
I got a bit further now, it will boot but now it gives for a split second the recovery screen before powering off the phone

**Comment by Robotix22** [comment]
Did you Try Windows in a VM? Maybe it will Detect it then Properly with USB Passthru
Windows Build 26100.1742 Detects the Device just Fine for me

**Comment by Ricca665** [comment]
i tried it, but it's 26100.1, and no vmware doesn't comnect to the pc, it gives driver error :/

**Comment by Robotix22** [comment]
VMWare Requires either a New Version of Linux or some User Fixes to Function curretly
Google should have many Resoults for that

**Comment by Ricca665** [comment]
basically under windows 11 when running the msc.sh script it gets recognized but it can't find the MTP drivers

i tried ALL the drivers i found but none of them worked

sry for the late reply
